from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WhatsAppAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("access_token", models.TextField()),
                ("phone_number_id", models.CharField(max_length=100)),
                ("waba_id", models.CharField(blank=True, max_length=100)),
                ("verify_token", models.CharField(default=uuid.uuid4, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"verbose_name": "WhatsApp Account", "verbose_name_plural": "WhatsApp Accounts"},
        ),
        migrations.CreateModel(
            name="WhatsAppAPIKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("key", models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"verbose_name": "API Key"},
        ),
        migrations.CreateModel(
            name="WhatsAppContact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("opted_out", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "Contact", "verbose_name_plural": "Contacts", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="WhatsAppWebhookLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("payload", models.JSONField()),
                ("processed", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True)),
            ],
            options={"ordering": ["-received_at"], "verbose_name": "Webhook Log"},
        ),
        migrations.CreateModel(
            name="WhatsAppConversation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone_number", models.CharField(max_length=30)),
                ("label", models.CharField(blank=True, choices=[("lead","Lead"),("customer","Customer"),("vip","VIP"),("support","Support"),("spam","Spam")], max_length=20)),
                ("is_resolved", models.BooleanField(default=False)),
                ("assigned_to", models.CharField(blank=True, max_length=255)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("unread_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="conversations", to="django_meta_whatsapp.whatsappaccount")),
                ("contact", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="conversations", to="django_meta_whatsapp.whatsappcontact")),
            ],
            options={"ordering": ["-last_message_at"], "verbose_name": "Conversation"},
        ),
        migrations.CreateModel(
            name="WhatsAppTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=512)),
                ("meta_template_id", models.CharField(blank=True, max_length=255)),
                ("language", models.CharField(default="en", max_length=10)),
                ("category", models.CharField(choices=[("MARKETING","Marketing"),("UTILITY","Utility"),("AUTHENTICATION","Authentication")], default="MARKETING", max_length=30)),
                ("status", models.CharField(choices=[("APPROVED","Approved"),("PENDING","Pending"),("REJECTED","Rejected"),("DRAFT","Draft")], default="DRAFT", max_length=20)),
                ("header", models.JSONField(blank=True, null=True)),
                ("body_text", models.TextField()),
                ("footer_text", models.CharField(blank=True, max_length=255)),
                ("buttons", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="templates", to="django_meta_whatsapp.whatsappaccount")),
            ],
            options={"verbose_name": "Template", "ordering": ["-created_at"], "unique_together": {("account", "name", "language")}},
        ),
        migrations.CreateModel(
            name="WhatsAppCampaign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("audience_type", models.CharField(default="contacts", max_length=50)),
                ("audience_filters", models.JSONField(blank=True, default=dict)),
                ("csv_file", models.FileField(blank=True, null=True, upload_to="whatsapp_campaign_csv/")),
                ("parameter_mappings", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("draft","Draft"),("scheduled","Scheduled"),("running","Running"),("completed","Completed"),("failed","Failed"),("paused","Paused")], default="draft", max_length=20)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("delivered_count", models.PositiveIntegerField(default=0)),
                ("read_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="campaigns", to="django_meta_whatsapp.whatsappaccount")),
                ("template", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="campaigns", to="django_meta_whatsapp.whatsapptemplate")),
            ],
            options={"ordering": ["-created_at"], "verbose_name": "Campaign"},
        ),
        migrations.CreateModel(
            name="WhatsAppCampaignRecipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone_number", models.CharField(max_length=30)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("pending","Pending"),("sent","Sent"),("delivered","Delivered"),("read","Read"),("failed","Failed")], default="pending", max_length=20)),
                ("message_id", models.CharField(blank=True, max_length=255, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("campaign", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recipients", to="django_meta_whatsapp.whatsappcampaign")),
            ],
            options={"verbose_name": "Campaign Recipient"},
        ),
        migrations.CreateModel(
            name="WhatsAppMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="whatsapp_media_library/")),
                ("media_id", models.CharField(blank=True, max_length=255)),
                ("media_type", models.CharField(choices=[("image","Image"),("video","Video"),("audio","Audio"),("document","Document")], max_length=20)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="media", to="django_meta_whatsapp.whatsappaccount")),
            ],
            options={"verbose_name": "Media", "verbose_name_plural": "Media Library"},
        ),
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone_number", models.CharField(max_length=30)),
                ("message_id", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ("message_type", models.CharField(choices=[("text","Text"),("image","Image"),("video","Video"),("audio","Audio"),("document","Document"),("location","Location"),("template","Template"),("reaction","Reaction"),("sticker","Sticker"),("interactive","Interactive"),("button","Button"),("unknown","Unknown")], default="text", max_length=20)),
                ("message_body", models.TextField(blank=True)),
                ("direction", models.CharField(choices=[("inbound","Inbound"),("outbound","Outbound")], max_length=10)),
                ("status", models.CharField(choices=[("sent","Sent"),("delivered","Delivered"),("read","Read"),("failed","Failed")], default="sent", max_length=20)),
                ("media_file", models.FileField(blank=True, null=True, upload_to="whatsapp_media/")),
                ("media_id", models.CharField(blank=True, max_length=255, null=True)),
                ("media_url", models.URLField(blank=True, max_length=1000, null=True)),
                ("media_mime_type", models.CharField(blank=True, max_length=100, null=True)),
                ("media_filename", models.CharField(blank=True, max_length=255, null=True)),
                ("location_latitude", models.FloatField(blank=True, null=True)),
                ("location_longitude", models.FloatField(blank=True, null=True)),
                ("location_name", models.CharField(blank=True, max_length=255)),
                ("location_address", models.TextField(blank=True)),
                ("reaction_emoji", models.CharField(blank=True, max_length=10)),
                ("reaction_to_message_id", models.CharField(blank=True, max_length=255)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_deleted", models.BooleanField(default=False)),
                ("raw_payload", models.JSONField(blank=True, null=True)),
                ("account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="messages", to="django_meta_whatsapp.whatsappaccount")),
                ("conversation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="messages", to="django_meta_whatsapp.whatsappconversation")),
                ("reply_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="replies", to="django_meta_whatsapp.whatsappmessage")),
            ],
            options={"ordering": ["timestamp"], "verbose_name": "Message"},
        ),
    ]
