# Generated by Django 6.0.6 on 2026-06-14 08:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Friendly label, e.g. 'My Business'", max_length=255)),
                ('access_token', models.TextField(help_text='Meta permanent / system-user access token')),
                ('phone_number_id', models.CharField(max_length=100)),
                ('waba_id', models.CharField(blank=True, max_length=100)),
                ('verify_token', models.CharField(default=uuid.uuid4, help_text='Webhook verify token', max_length=255)),
                ('profile_name', models.CharField(blank=True, help_text='Fetched via Graph API', max_length=255)),
                ('profile_picture_url', models.URLField(blank=True, help_text='Fetched via Graph API', max_length=1024)),
                ('default_catalog_id', models.CharField(blank=True, help_text='Default Meta Commerce Catalog ID', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Account',
                'verbose_name_plural': 'WhatsApp Accounts',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'API Key',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('opted_out', models.BooleanField(default=False, help_text='Contact has opted out of marketing')),
                ('is_blocked', models.BooleanField(default=False, help_text='Synced from WhatsAppBlockedUser — for fast inbox UI filtering')),
                ('subscribed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='gray', help_text='Tailwind color or hex', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Labels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Webhook Log',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('audience_type', models.CharField(default='contacts', help_text="'contacts', 'csv', or an AUDIENCES key from settings", max_length=50)),
                ('audience_filters', models.JSONField(blank=True, default=dict, help_text='Extra filter kwargs passed to audience provider')),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='whatsapp_campaign_csv/')),
                ('parameter_mappings', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('read_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='django_meta_whatsapp.whatsappaccount')),
            ],
            options={
                'verbose_name': 'Campaign',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppCampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Resolved template variables for this recipient')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='django_meta_whatsapp.whatsappcampaign')),
            ],
            options={
                'verbose_name': 'Campaign Recipient',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('is_resolved', models.BooleanField(default=False)),
                ('assigned_to', models.CharField(blank=True, help_text='Agent username or email', max_length=255)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='django_meta_whatsapp.whatsappaccount')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='django_meta_whatsapp.whatsappcontact')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='django_meta_whatsapp.whatsapplabel')),
            ],
            options={
                'verbose_name': 'Conversation',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.AddField(
            model_name='whatsappcontact',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='django_meta_whatsapp.whatsapplabel'),
        ),
        migrations.CreateModel(
            name='WhatsAppMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='whatsapp_media_library/')),
                ('media_id', models.CharField(blank=True, help_text='ID returned by Meta after upload', max_length=255)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document')], max_length=20)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='django_meta_whatsapp.whatsappaccount')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media Library',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('location', 'Location'), ('template', 'Template'), ('reaction', 'Reaction'), ('sticker', 'Sticker'), ('interactive', 'Interactive'), ('button', 'Button'), ('unknown', 'Unknown')], default='text', max_length=20)),
                ('message_body', models.TextField(blank=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='whatsapp_media/')),
                ('media_id', models.CharField(blank=True, help_text='Meta media ID', max_length=255, null=True)),
                ('media_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('media_mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('media_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('location_latitude', models.FloatField(blank=True, null=True)),
                ('location_longitude', models.FloatField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('location_address', models.TextField(blank=True)),
                ('reaction_emoji', models.CharField(blank=True, max_length=10)),
                ('reaction_to_message_id', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(blank=True, help_text='Full webhook payload for debugging', null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='django_meta_whatsapp.whatsappaccount')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='django_meta_whatsapp.whatsappconversation')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='django_meta_whatsapp.whatsappmessage')),
            ],
            options={
                'verbose_name': 'Message',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_id', models.CharField(blank=True, help_text='ID returned by Meta after creation', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Internal label, not shown to users', max_length=255)),
                ('signup_message', models.TextField(help_text='Pre-consent screen text shown to user in WhatsApp')),
                ('confirmation_message', models.TextField(help_text='Sent to user after they subscribe. Use {{promo_code}} for promo.')),
                ('privacy_policy_url', models.URLField(help_text='Immutable after creation on Meta')),
                ('website_url', models.URLField(blank=True)),
                ('promo_code', models.CharField(blank=True, help_text='Alphanumeric only. Replaces {{promo_code}} in confirmation message.', max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=20)),
                ('subscriber_count', models.PositiveIntegerField(default=0)),
                ('tos_accepted', models.BooleanField(default=False, help_text='True after Terms of Service accepted on first creation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='django_meta_whatsapp.whatsappaccount')),
                ('auto_add_to_label', models.ForeignKey(blank=True, help_text='Automatically assign this label to users who subscribe via this link', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_meta_whatsapp.whatsapplabel')),
            ],
            options={
                'verbose_name': 'In-App Signup',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='whatsappcontact',
            name='subscribed_via_signup',
            field=models.ForeignKey(blank=True, help_text='Which signup link brought this contact in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='django_meta_whatsapp.whatsappsignup'),
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('meta_template_id', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(default='en', max_length=10)),
                ('category', models.CharField(choices=[('MARKETING', 'Marketing'), ('UTILITY', 'Utility'), ('AUTHENTICATION', 'Authentication')], default='MARKETING', max_length=30)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('DRAFT', 'Draft')], default='DRAFT', max_length=20)),
                ('header', models.JSONField(blank=True, help_text='{"type": "TEXT"|"IMAGE"|"VIDEO"|"DOCUMENT", "text": "..."}', null=True)),
                ('body_text', models.TextField(help_text='Use {{1}}, {{2}} for variables')),
                ('footer_text', models.CharField(blank=True, max_length=255)),
                ('buttons', models.JSONField(blank=True, default=list, help_text='[{"type":"QUICK_REPLY","text":"Yes"}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='django_meta_whatsapp.whatsappaccount')),
            ],
            options={
                'verbose_name': 'Template',
                'ordering': ['-created_at'],
                'unique_together': {('account', 'name', 'language')},
            },
        ),
        migrations.AddField(
            model_name='whatsappcampaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='django_meta_whatsapp.whatsapptemplate'),
        ),
        migrations.CreateModel(
            name='WhatsAppBlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('wa_id', models.CharField(blank=True, max_length=50)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_by', models.CharField(blank=True, help_text='Username/email of agent who triggered the block', max_length=255)),
                ('reason', models.TextField(blank=True, help_text='Internal note — spam, abuse, etc.')),
                ('is_active', models.BooleanField(default=True, help_text='False means unblocked — kept for audit history')),
                ('unblocked_at', models.DateTimeField(blank=True, null=True)),
                ('unblocked_by', models.CharField(blank=True, max_length=255)),
                ('meta_error', models.TextField(blank=True, help_text='Stores error detail if Meta block call failed')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to='django_meta_whatsapp.whatsappaccount')),
            ],
            options={
                'verbose_name': 'Blocked User',
                'ordering': ['-blocked_at'],
                'unique_together': {('account', 'phone_number')},
            },
        ),
        migrations.CreateModel(
            name='WhatsAppCatalogProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_id', models.CharField(max_length=255)),
                ('retailer_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_products', to='django_meta_whatsapp.whatsappaccount')),
            ],
            options={
                'verbose_name': 'Catalog Product',
                'unique_together': {('account', 'catalog_id', 'retailer_id')},
            },
        ),
    ]
