# Generated by Django 6.0.6 on 2026-06-26 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_meta_whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('meta_flow_id', models.CharField(blank=True, help_text='ID returned by Meta after creation via Graph API', max_length=100)),
                ('categories', models.JSONField(default=list, help_text='e.g. ["CUSTOMER_SUPPORT"] — choose from CATEGORY_CHOICES')),
                ('flow_json', models.JSONField(default=dict, help_text='Complete Flow JSON — see https://developers.facebook.com/docs/whatsapp/flows/reference/flowjson')),
                ('is_dynamic', models.BooleanField(default=False, help_text='True if this flow calls your server endpoint between screens')),
                ('endpoint_uri', models.URLField(blank=True, help_text='For dynamic flows only — the HTTPS endpoint Meta will call')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('DEPRECATED', 'Deprecated'), ('BLOCKED', 'Blocked'), ('THROTTLED', 'Throttled')], default='DRAFT', max_length=20)),
                ('validation_errors', models.JSONField(default=list, help_text="Populated after a flow JSON upload attempt from Meta's response")),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('completion_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='django_meta_whatsapp.whatsappaccount')),
            ],
            options={
                'verbose_name': 'WhatsApp Flow',
                'verbose_name_plural': 'WhatsApp Flows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppFlowResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('response_data', models.JSONField(help_text='The payload object submitted by the user in the flow')),
                ('flow_token', models.CharField(blank=True, help_text="Meta's flow_token from the webhook payload", max_length=512)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False, help_text='Set to True by the host project after the response has been handled')),
                ('raw_payload', models.JSONField(blank=True, help_text='Full webhook message payload for debugging', null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_responses', to='django_meta_whatsapp.whatsappconversation')),
                ('flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='django_meta_whatsapp.whatsappflow')),
            ],
            options={
                'verbose_name': 'Flow Response',
                'verbose_name_plural': 'Flow Responses',
                'ordering': ['-completed_at'],
            },
        ),
    ]
